spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yidai_blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  messages:
    basename: i18n/messages

# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

mybatis:
  # 设置别名
  type-aliases-package: com.yidai.pojo
  # 指定myBatis的核心配置文件与Mapper映射文件
  mapper-locations: classpath:mapper/*.xml

logging:
  # 日志级别
  level:
    root: info
    com.blog: debug
  file:
    path: P:/log/yidai_blog/

comment.avatar: /images/avatar.jpg

server:
  port: 8080